/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  auth: {
    NewAccount: () => import('#controllers/auth/new_account_controller'),
    Profile: () => import('#controllers/auth/profile_controller'),
    Session: () => import('#controllers/auth/session_controller'),
  },
  inventory: {
    Equipment: () => import('#controllers/inventory/equipment_controller'),
  },
  reports: {
    Dashboard: () => import('#controllers/reports/dashboard_controller'),
  },
  settings: {
    Headquarters: () => import('#controllers/settings/headquarters_controller'),
    Locations: () => import('#controllers/settings/locations_controller'),
  },
}
