/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  alerts: {
    Alerts: () => import('#controllers/alerts/alerts_controller'),
  },
  auth: {
    NewAccount: () => import('#controllers/auth/new_account_controller'),
    Profile: () => import('#controllers/auth/profile_controller'),
    Session: () => import('#controllers/auth/session_controller'),
  },
  chat: {
    Chat: () => import('#controllers/chat/chat_controller'),
  },
  inventory: {
    EquipmentAssignments: () => import('#controllers/inventory/equipment_assignments_controller'),
    EquipmentAttachments: () => import('#controllers/inventory/equipment_attachments_controller'),
    EquipmentCatalogs: () => import('#controllers/inventory/equipment_catalogs_controller'),
    Equipment: () => import('#controllers/inventory/equipment_controller'),
    EquipmentGroups: () => import('#controllers/inventory/equipment_groups_controller'),
    EquipmentLoans: () => import('#controllers/inventory/equipment_loans_controller'),
    EquipmentTypes: () => import('#controllers/inventory/equipment_types_controller'),
    FailureReports: () => import('#controllers/inventory/failure_reports_controller'),
    MaintenanceRecordAttachments: () => import('#controllers/inventory/maintenance_record_attachments_controller'),
    MaintenanceRecords: () => import('#controllers/inventory/maintenance_records_controller'),
    MaintenanceSchedules: () => import('#controllers/inventory/maintenance_schedules_controller'),
  },
  realtime: {
    RealtimeTokens: () => import('#controllers/realtime/realtime_tokens_controller'),
  },
  reports: {
    Dashboard: () => import('#controllers/reports/dashboard_controller'),
  },
  settings: {
    Headquarters: () => import('#controllers/settings/headquarters_controller'),
    Locations: () => import('#controllers/settings/locations_controller'),
  },
  system: {
    SystemLogs: () => import('#controllers/system/system_logs_controller'),
  },
  users: {
    Users: () => import('#controllers/users/users_controller'),
  },
}
