/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'id', 'lastUsedAt', 'name', 'tokenHash', 'updatedAt', 'userId'] as const
  $columns = AccessTokenSchema.$columns
  @column()
  declare abilities: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string
  @column()
  declare tokenHash: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class AttachmentSchema extends BaseModel {
  static $columns = ['createdAt', 'entityId', 'entityType', 'fileName', 'filePath', 'id', 'mimeType', 'sizeBytes', 'uploadedBy'] as const
  $columns = AttachmentSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: string
  @column()
  declare entityType: any
  @column()
  declare fileName: string
  @column()
  declare filePath: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare mimeType: string | null
  @column()
  declare sizeBytes: bigint | number | null
  @column()
  declare uploadedBy: string | null
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'createdAt', 'entityId', 'entityType', 'id', 'ipAddress', 'newValues', 'oldValues', 'userAgent', 'userId'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: string | null
  @column()
  declare entityType: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare newValues: any | null
  @column()
  declare oldValues: any | null
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string | null
}

export class EquipmentSchema extends BaseModel {
  static $columns = ['assetTag', 'brand', 'createdAt', 'createdBy', 'currentResponsibleId', 'deletedAt', 'headquarterId', 'id', 'internalCode', 'lastMaintenanceAt', 'leaseContractNumber', 'leaseProvider', 'leaseUntil', 'locationId', 'model', 'nextMaintenanceAt', 'notes', 'ownershipType', 'purchaseDate', 'serial', 'status', 'type', 'updatedAt', 'updatedBy', 'warrantyUntil'] as const
  $columns = EquipmentSchema.$columns
  @column()
  declare assetTag: string | null
  @column()
  declare brand: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column()
  declare currentResponsibleId: string | null
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare headquarterId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare internalCode: string
  @column.date()
  declare lastMaintenanceAt: DateTime | null
  @column()
  declare leaseContractNumber: string | null
  @column()
  declare leaseProvider: string | null
  @column.date()
  declare leaseUntil: DateTime | null
  @column()
  declare locationId: string | null
  @column()
  declare model: string | null
  @column.date()
  declare nextMaintenanceAt: DateTime | null
  @column()
  declare notes: string | null
  @column()
  declare ownershipType: any
  @column.date()
  declare purchaseDate: DateTime | null
  @column()
  declare serial: string
  @column()
  declare status: any
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
  @column.date()
  declare warrantyUntil: DateTime | null
}

export class EquipmentAssignmentSchema extends BaseModel {
  static $columns = ['assignedAt', 'assignedBy', 'createdAt', 'equipmentId', 'id', 'notes', 'returnedAt', 'updatedAt', 'userId'] as const
  $columns = EquipmentAssignmentSchema.$columns
  @column.dateTime()
  declare assignedAt: DateTime
  @column()
  declare assignedBy: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare equipmentId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare notes: string | null
  @column.dateTime()
  declare returnedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class FailureReportSchema extends BaseModel {
  static $columns = ['closedAt', 'createdAt', 'description', 'equipmentId', 'id', 'maintenanceRecordId', 'priority', 'reportedBy', 'status', 'title', 'updatedAt'] as const
  $columns = FailureReportSchema.$columns
  @column.dateTime()
  declare closedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare equipmentId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare maintenanceRecordId: string | null
  @column()
  declare priority: any
  @column()
  declare reportedBy: string | null
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class HeadquartersSchema extends BaseModel {
  static $columns = ['address', 'city', 'createdAt', 'description', 'id', 'isActive', 'name', 'updatedAt'] as const
  $columns = HeadquartersSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare city: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class LocationSchema extends BaseModel {
  static $columns = ['area', 'createdAt', 'description', 'floor', 'headquarterId', 'id', 'isActive', 'office', 'updatedAt'] as const
  $columns = LocationSchema.$columns
  @column()
  declare area: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare floor: string | null
  @column()
  declare headquarterId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare office: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MaintenanceRecordSchema extends BaseModel {
  static $columns = ['actionsTaken', 'cost', 'createdAt', 'createdBy', 'description', 'diagnosis', 'equipmentId', 'id', 'maintenanceScheduleId', 'maintenanceType', 'nextMaintenanceAt', 'partsReplaced', 'performedAt', 'performedBy', 'priority', 'scheduledDate', 'status', 'updatedAt', 'updatedBy'] as const
  $columns = MaintenanceRecordSchema.$columns
  @column()
  declare actionsTaken: string | null
  @column()
  declare cost: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column()
  declare description: string | null
  @column()
  declare diagnosis: string | null
  @column()
  declare equipmentId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare maintenanceScheduleId: string | null
  @column()
  declare maintenanceType: any
  @column.date()
  declare nextMaintenanceAt: DateTime | null
  @column()
  declare partsReplaced: string | null
  @column.dateTime()
  declare performedAt: DateTime | null
  @column()
  declare performedBy: string | null
  @column()
  declare priority: any
  @column.date()
  declare scheduledDate: DateTime | null
  @column()
  declare status: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
}

export class MaintenanceScheduleSchema extends BaseModel {
  static $columns = ['assignedTechnicianId', 'createdAt', 'createdBy', 'equipmentId', 'frequencyMonths', 'id', 'maintenanceType', 'notes', 'priority', 'scheduledFor', 'status', 'updatedAt', 'updatedBy'] as const
  $columns = MaintenanceScheduleSchema.$columns
  @column()
  declare assignedTechnicianId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: string | null
  @column()
  declare equipmentId: string
  @column()
  declare frequencyMonths: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare maintenanceType: any
  @column()
  declare notes: string | null
  @column()
  declare priority: any
  @column.date()
  declare scheduledFor: DateTime
  @column()
  declare status: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
}

export class PermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = PermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'permissionId', 'roleId'] as const
  $columns = RolePermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare permissionId: string
  @column()
  declare roleId: string
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isActive', 'name', 'slug', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'department', 'email', 'id', 'isActive', 'jobTitle', 'lastLoginAt', 'name', 'password', 'phone', 'roleId', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare department: string | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare jobTitle: string | null
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare roleId: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
